language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

os:
  - linux
  - osx

before_script:
  - composer self-update
  - composer install -o --prefer-source
  - mkdir tests/resources/cache/
  - chmod -R 777 tests/resources/cache/

script:
# xdebug is not installed on HHVM and PHP 7, so we are skipping the creation of code coverage data there
  - if [ "`phpenv version-name`" == "5.3" ] || [ "`phpenv version-name`" == "5.4" ] || [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then vendor/bin/phpunit --colors --verbose --coverage-clover=coverage.clover; fi
  - if [ "`phpenv version-name`" != "5.3" ] && [ "`phpenv version-name`" != "5.4" ] && [ "`phpenv version-name`" != "5.5" ] && [ "`phpenv version-name`" != "5.6" ]; then vendor/bin/phpunit --colors --verbose; fi
  - vendor/bin/phpcs --standard=psr2 -np src tests

after_script:
  - rm -R -f -d tests/resources/cache/
  - rmdir tests/resources/cache/
# xdebug is not installed on HHVM and PHP 7, so we have no code coverage data to send
  - if [ "`phpenv version-name`" == "5.3" ] || [ "`phpenv version-name`" == "5.4" ] || [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "`phpenv version-name`" == "5.3" ] || [ "`phpenv version-name`" == "5.4" ] || [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

notifications:
  email: false
