language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

os:
  - linux
  - osx

before_script:
  - if [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - composer self-update
  - composer install -o --prefer-source
  - mkdir tests/resources/cache/
  - chmod -R 777 tests/resources/cache/

script:
  - phpunit --configuration travis.phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover --colors --verbose

after_script:
  - rm -R -f -d tests/resources/cache/
  - rmdir tests/resources/cache/
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover